;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.5
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :xcb)



;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cl:defconstant #.(custom-lispify "POLLIN" 'constant) #x0001)

(cl:export '#.(custom-lispify "POLLIN" 'constant))

(cl:defconstant #.(custom-lispify "POLLPRI" 'constant) #x0002)

(cl:export '#.(custom-lispify "POLLPRI" 'constant))

(cl:defconstant #.(custom-lispify "POLLOUT" 'constant) #x0004)

(cl:export '#.(custom-lispify "POLLOUT" 'constant))

(cl:defconstant #.(custom-lispify "POLLERR" 'constant) #x0008)

(cl:export '#.(custom-lispify "POLLERR" 'constant))

(cl:defconstant #.(custom-lispify "POLLHUP" 'constant) #x0010)

(cl:export '#.(custom-lispify "POLLHUP" 'constant))

(cl:defconstant #.(custom-lispify "POLLNVAL" 'constant) #x0020)

(cl:export '#.(custom-lispify "POLLNVAL" 'constant))

(cl:defconstant #.(custom-lispify "_SYS_POLL_H" 'constant) 1)

(cl:export '#.(custom-lispify "_SYS_POLL_H" 'constant))

(cffi:defctype #.(custom-lispify "nfds_t" 'typename) :unsigned-long)

(cl:export '#.(custom-lispify "nfds_t" 'typename))


